logging:
  level: INFO

jdbc:
  port_number:
    mssql: 1433
    postgresql: 5432

  class_name:
    mssql: com.microsoft.sqlserver.jdbc.SQLServerDriver
    postgresql: org.postgresql.Driver

  jar:
    mssql: lib/jars/mssql-jdbc-12.4.2.jre11.jar
    postgresql: lib/jars/postgresql-42.7.0.jar

  connection_string:
    mssql: jdbc:sqlserver://put_host_name_here:put_port_number_here;databaseName=put_database_name_here;trustServerCertificate=true
    postgresql: jdbc:postgresql://put_host_name_here:put_port_number_here/put_database_name_here

  column_info:
    mssql: "
      select 
        column_name, 
        is_nullable, 
        data_type, 
        character_maximum_length, 
        numeric_precision, 
        numeric_precision_radix, 
        numeric_scale, 
        datetime_precision 
      from 
        information_schema.columns 
      where 
        table_schema = ? 
        and table_name = ? 
      order by 
        ordinal_position
      "
    postgresql: " 
      select 
        column_name, 
        is_nullable, 
        data_type, 
        character_maximum_length, 
        numeric_precision, 
        numeric_precision_radix, 
        numeric_scale, 
        datetime_precision 
      from 
        information_schema.columns 
      where 
        table_schema = ? 
        and table_name = ? 
      order by 
        ordinal_position
      "
